application: volcanicpixels-updates
version: 1
runtime: python27
api_version: 1
threadsafe: yes




handlers:

- url: /favicon.ico
  static_files: application/static/img/favicon.ico
  upload: application/static/img/favicon.ico

- url: /robots.txt
  static_files: application/static/robots.txt
  upload: application/static/robots.txt

- url: /mu-84c1db53-b95e408f-a1aa8605-55acbf1b.txt
  static_files: application/static/mu-84c1db53-b95e408f-a1aa8605-55acbf1b.txt
  upload: application/static/mu-84c1db53-b95e408f-a1aa8605-55acbf1b.txt

- url: .*
  script: application.app


- url: .*
  script: page_handlers.app




libraries:
- name: webapp2
  version: "2.5.2"
- name: jinja2
  version: "2.6"
- name: markupsafe
  version: "0.15"



builtins:
- appstats: on
- remote_api: on
- deferred: on


inbound_services:
- warmup



error_handlers:
- file: error_pages/default_error.html
- error_code: over_quota
  file: error_pages/over_quota.html
- error_code: dos_api_denial
  file: error_pages/dos_api_denial.html
- error_code: timeout
  file: error_pages/timeout.html